# Generated by Django 3.2.4 on 2021-06-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_doors_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialstory',
            name='attraction',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
