# Generated by Django 3.2.4 on 2021-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_doors_api', '0002_socialstory_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
