# Generated by Django 3.2.4 on 2021-06-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='VisualSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('activity_1', models.CharField(max_length=200)),
                ('image_1', models.TextField()),
                ('activity_2', models.CharField(max_length=200)),
                ('image_2', models.TextField()),
                ('activity_3', models.CharField(max_length=200)),
                ('image_3', models.TextField()),
                ('activity_4', models.CharField(max_length=200)),
                ('image_4', models.TextField()),
                ('activity_5', models.CharField(max_length=200)),
                ('image_5', models.TextField()),
                ('activity_6', models.CharField(max_length=200)),
                ('image_6', models.TextField()),
                ('activity_7', models.CharField(max_length=200)),
                ('image_7', models.TextField()),
                ('activity_8', models.CharField(max_length=200)),
                ('image_8', models.TextField()),
                ('activity_9', models.CharField(max_length=200)),
                ('image_9', models.TextField()),
                ('activity_10', models.CharField(max_length=200)),
                ('image_10', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('titlepage', models.TextField()),
                ('title_image', models.TextField()),
                ('page_1_text', models.TextField()),
                ('page_1_image', models.TextField()),
                ('page_2_text', models.TextField()),
                ('page_2_image', models.TextField()),
                ('page_3_text', models.TextField()),
                ('page_3_image', models.TextField()),
                ('page_4_text', models.TextField()),
                ('page_4_image', models.TextField()),
                ('page_5_text', models.TextField()),
                ('page_5_image', models.TextField()),
                ('page_6_text', models.TextField()),
                ('page_6_image', models.TextField()),
                ('page_7_text', models.TextField()),
                ('page_7_image', models.TextField()),
                ('page_8_text', models.TextField()),
                ('page_8_image', models.TextField()),
                ('page_9_text', models.TextField()),
                ('page_9_image', models.TextField()),
                ('page_10_text', models.TextField()),
                ('page_10_image', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('approved', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_doors_api.category')),
                ('social_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_doors_api.socialstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visual_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_doors_api.visualschedule')),
            ],
        ),
        migrations.CreateModel(
            name='OpenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
