# Generated by Django 3.2.4 on 2021-06-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_doors_api', '0004_alter_post_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='social_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_doors_api.socialstory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visual_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_doors_api.visualschedule'),
        ),
    ]
